# Generated by Django 3.2.9 on 2022-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cn_Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_Name', models.CharField(max_length=69, unique=True)),
                ('Party', models.CharField(max_length=60, unique=True)),
                ('Mobile', models.CharField(max_length=13, unique=True)),
                ('Gender', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=69)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=100)),
                ('Aadhar', models.CharField(max_length=12, unique=True)),
                ('VoterID', models.CharField(max_length=10, unique=True)),
                ('DOB', models.DateField(default='2022/07/08')),
            ],
        ),
    ]
