# Generated by Django 3.2.9 on 2022-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BJP', models.CharField(max_length=13)),
                ('INC', models.CharField(max_length=13)),
                ('BSP', models.CharField(max_length=13)),
                ('TMC', models.CharField(max_length=13)),
                ('NCP', models.CharField(max_length=13)),
                ('NPP', models.CharField(max_length=13)),
                ('AAP', models.CharField(max_length=13)),
                ('JDU', models.CharField(max_length=13)),
                ('RJD', models.CharField(max_length=13)),
                ('SP', models.CharField(max_length=13)),
                ('CPI', models.CharField(max_length=13)),
                ('CPIM', models.CharField(max_length=13)),
                ('RLD', models.CharField(max_length=13)),
                ('NOTA', models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name='registeration',
            name='DOB',
            field=models.DateField(default='2022/07/09'),
        ),
    ]
