# Generated by Django 3.2.9 on 2022-07-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220714_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='VoterID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='DOB',
            field=models.DateField(default='2022/07/15'),
        ),
    ]
