# Generated by Django 3.2.9 on 2022-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220710_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='cn_registeration',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
