# Generated by Django 3.2.9 on 2022-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220715_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='AAP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='BJP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='BSP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='CPI',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='CPIM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='INC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='JDU',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='NCP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='NOTA',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='NPP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='RJD',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='RLD',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='SP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='TMC',
            field=models.IntegerField(default=0),
        ),
    ]
