# Generated by Django 3.2.9 on 2022-07-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cn_registeration_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='DOB',
            field=models.DateField(default='2022/07/11'),
        ),
    ]
