# Generated by Django 3.2.9 on 2022-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_registeration_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cn_registeration',
            old_name='resume',
            new_name='doc_file',
        ),
        migrations.AlterField(
            model_name='registeration',
            name='DOB',
            field=models.DateField(default='2022/07/12'),
        ),
    ]
